### ISSUE TITLE
你好,请问Jackson 利用链适用版本是多少 com.fasterxml.jackson.core:jackson-databind 2.7.4能利用吗

### ISSUE THREAD

**Issue by xyy6661231** [X1r0z/JNDIMap#6]
你好,请问Jackson 利用链适用版本是多少 com.fasterxml.jackson.core:jackson-databind 2.7.4能利用吗

**Comment by X1r0z** [comment]
师傅可以本地自行测试一下, 我如果记得没错的话过版本太低的 Jackson 依赖是不行的
